@echo off
setlocal EnableDelayedExpansion

if "%~1"=="" (
    echo [ERROR] No target project path provided.
    echo Usage: %~nx0 ^<Project_Directory^> [--hdl-ext v^|sv]
    pause
    exit /b 1
)

set "TARGET_PROJECT=%~f1"
set "HDL_EXT=v"
set "ARG2=%~2"
if /i "%~2"=="--hdl-ext" (
    if /i "%~3"=="sv" set "HDL_EXT=sv"
    if /i "%~3"=="v" set "HDL_EXT=v"
) else if /i "!ARG2:~0,10!"=="--hdl-ext=" (
    set "HDL_EXT=!ARG2:~10!"
)
if /i not "%HDL_EXT%"=="v" if /i not "%HDL_EXT%"=="sv" set "HDL_EXT=v"
cd /d "%TARGET_PROJECT%"
echo Target Project: %TARGET_PROJECT%

echo -----------------------------------------------------------
echo      HDL Module Generator (Verilog/SystemVerilog)
echo -----------------------------------------------------------

:: Run PowerShell
set "PS_FILE=%TEMP%\create_mod_%RANDOM%.ps1"
set "MARKER=:POWERSHELL_SCRIPT_START"

for /f "tokens=1 delims=:" %%a in ('findstr /n "^%MARKER%" "%~f0"') do set "START_LINE=%%a"
more +%START_LINE% "%~f0" > "%PS_FILE%"

powershell -NoProfile -ExecutionPolicy Bypass -File "%PS_FILE%" "%HDL_EXT%"

del "%PS_FILE%"
goto :eof

:POWERSHELL_SCRIPT_START
param(
    [string]$HdlExt = "v"
)
$srcDir = 'src';
if (-not (Test-Path $srcDir)) { New-Item -ItemType Directory -Path $srcDir | Out-Null }
if ($HdlExt -notin @("v", "sv")) { $HdlExt = "v" }

Write-Host "Enter Module Name (e.g. MyCounter):" -ForegroundColor Cyan
$mName = Read-Host " >"
$mName = $mName.Trim()

if ([string]::IsNullOrWhiteSpace($mName)) {
    Write-Host "Name cannot be empty." -ForegroundColor Red
    exit
}

$fileName = "$srcDir\$mName.$HdlExt"
if (Test-Path $fileName) {
    Write-Host "File already exists!" -ForegroundColor Red
    exit
}

Write-Host "Enter Ports (format: name width, comma separated)" -ForegroundColor Cyan
Write-Host "Example: clk, rst, data_in [7:0], count_out [3:0]" -ForegroundColor Gray
$rawPorts = Read-Host " >"

# --- Parse Ports ---
$ports = @()

# Use regex to find "name" and optional "[width]"
# Patterns: "clk", "rst", "bus [7:0]"
# We split by comma first
$tokens = $rawPorts -split ','
foreach ($t in $tokens) {
    $t = $t.Trim()
    if ($t -eq "") { continue }
    
    $width = ""
    $name = $t
    
    # Check width
    if ($t -match '\[.*?\]') {
        $width = $matches[0]
        $name = $t.Replace($width, "").Trim()
    }
    
    # Guess Direction (Convention)
    $dir = "input"
    if ($name -match '(?i)^io[A-Z0-9_]' -or $name -match '(?i)\binout\b') { $dir = "inout" }
    elseif ($name -match '(?i)^o[A-Z0-9_]' -or $name -match '(?i)^o_' -or $name -match '(?i)_out$') { $dir = "output" }
    elseif ($name -match '(?i)^i[A-Z0-9_]') { $dir = "input" }
    
    # Special: clk, rst are inputs
    if ($name -match 'clk' -or $name -match 'rst' -or $name -match 'reset') { $dir = "input" }

    # For output, usually we want 'output reg' if we use it in always block, 
    # but for safety let's stick to wire/reg separation or just output.
    # Let's use 'output reg' by default for convenience in always blocks? 
    # Actually 'output' is wire by default, but let's make it 'output'
    
    $ports += @{ Name=$name; Width=$width; Dir=$dir }
}

# --- Generate Code ---
$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine('`timescale 1ns / 1ps')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('/*')
[void]$sb.AppendLine('[MODULE_INFO_START]')
[void]$sb.AppendLine("Name: $mName")
[void]$sb.AppendLine("Role: RTL module implementing $mName")
[void]$sb.AppendLine('Summary:')
[void]$sb.AppendLine('  - Generated by code_verilog_module_generate.bat')
[void]$sb.AppendLine('  - Fill behavior/FSM description before review')
[void]$sb.AppendLine('[MODULE_INFO_END]')
[void]$sb.AppendLine('*/')
[void]$sb.AppendLine('')
[void]$sb.AppendLine("module $mName (")

for ($i=0; $i -lt $ports.Count; $i++) {
    $p = $ports[$i]
    $comma = if ($i -lt $ports.Count - 1) { "," } else { "" }
    
    $decl = "    $($p.Dir)"
    if ($HdlExt -eq "sv") {
        if ($p.Dir -eq "inout") {
            $decl += " wire"
        } else {
            $decl += " logic"
        }
    } else {
        if ($p.Dir -eq "output") { $decl += " reg" } # Make outputs reg for convenience
    }
    if ($p.Width -ne "") { $decl += " $($p.Width)" }
    $decl += " $($p.Name)$comma"
    
    [void]$sb.AppendLine($decl)
}
[void]$sb.AppendLine(');')
[void]$sb.AppendLine('')
[void]$sb.AppendLine("    // Internal Signals")
[void]$sb.AppendLine('')

$clockPort = $null
$resetPort = $null
$isActiveLowReset = $false
foreach ($p in $ports) {
    if ($p.Dir -eq "input" -and -not $clockPort -and ($p.Name -match '(?i)(^i?clk$|clock|clk_|^iClk)')) {
        $clockPort = $p.Name
    }
    if ($p.Dir -eq "input" -and -not $resetPort -and ($p.Name -match '(?i)(^i?rst|reset|rstn$|iRstn$)')) {
        $resetPort = $p.Name
        # Check for active-low reset pattern (ends with 'n' like iRstn, rstn)
        if ($p.Name -match '(?i)n$') {
            $isActiveLowReset = $true
        }
    }
}

if ($clockPort) {
    if ($resetPort) {
        if ($isActiveLowReset) {
            # Active-low reset (iRstn style)
            if ($HdlExt -eq "sv") {
                [void]$sb.AppendLine("    always_ff @(posedge $clockPort or negedge $resetPort) begin")
            } else {
                [void]$sb.AppendLine("    always @(posedge $clockPort or negedge $resetPort) begin")
            }
            [void]$sb.AppendLine("        if (!$resetPort) begin")
        } else {
            # Active-high reset (iRst style)
            if ($HdlExt -eq "sv") {
                [void]$sb.AppendLine("    always_ff @(posedge $clockPort or posedge $resetPort) begin")
            } else {
                [void]$sb.AppendLine("    always @(posedge $clockPort or posedge $resetPort) begin")
            }
            [void]$sb.AppendLine("        if ($resetPort) begin")
        }
        [void]$sb.AppendLine("            // Reset Logic")
        foreach ($p in $ports) {
            if ($p.Dir -eq "output") {
                [void]$sb.AppendLine("            $($p.Name) <= 0;")
            }
        }
        [void]$sb.AppendLine("        end else begin")
        [void]$sb.AppendLine("            // Main Logic")
        [void]$sb.AppendLine("        end")
        [void]$sb.AppendLine("    end")
    } else {
        if ($HdlExt -eq "sv") {
            [void]$sb.AppendLine("    always_ff @(posedge $clockPort) begin")
        } else {
            [void]$sb.AppendLine("    always @(posedge $clockPort) begin")
        }
        [void]$sb.AppendLine("        // Sequential Logic")
        [void]$sb.AppendLine("    end")
    }
} else {
    if ($HdlExt -eq "sv") {
        [void]$sb.AppendLine("    always_comb begin")
    } else {
        [void]$sb.AppendLine("    always @* begin")
    }
    foreach ($p in $ports) {
        if ($p.Dir -eq "output") {
            [void]$sb.AppendLine("        $($p.Name) = 0;")
        }
    }
    [void]$sb.AppendLine("        // Combinational Logic")
    [void]$sb.AppendLine("    end")
}
[void]$sb.AppendLine('')
[void]$sb.AppendLine('endmodule')

Set-Content -Path $fileName -Value $sb.ToString()
Write-Host "Created: $fileName" -ForegroundColor Green

# Open in Editor
if (Get-Command "code" -ErrorAction SilentlyContinue) {
    code -r $fileName
} else {
    Invoke-Item $fileName
}
