const fs = require("fs");
const path = require("path");

function slugify(text) {
  return String(text || "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .slice(0, 64) || "run";
}

function uniqueSortedPaths(rows) {
  return Array.from(new Set((rows || []).map((row) => path.resolve(row))))
    .sort((a, b) => a.localeCompare(b));
}

function isPathWithin(parentAbs, targetAbs) {
  const parent = path.resolve(parentAbs);
  const target = path.resolve(targetAbs);
  const rel = path.relative(parent, target);
  return rel === "" || (!rel.startsWith("..") && !path.isAbsolute(rel));
}

function toTclPath(value) {
  return String(value || "").replace(/\\/g, "/");
}

function toTclList(paths) {
  return (paths || []).map((row) => `{${toTclPath(row)}}`).join(" ");
}

function findLatestFileRecursive(rootDir, ext) {
  if (!fs.existsSync(rootDir)) return null;
  let latest = null;
  const stack = [rootDir];
  while (stack.length > 0) {
    const cur = stack.pop();
    const entries = fs.readdirSync(cur, { withFileTypes: true });
    for (const entry of entries) {
      const abs = path.join(cur, entry.name);
      if (entry.isDirectory()) {
        stack.push(abs);
        continue;
      }
      if (!entry.isFile()) continue;
      if (path.extname(entry.name).toLowerCase() !== ext) continue;
      const mtimeMs = fs.statSync(abs).mtimeMs;
      if (!latest || mtimeMs > latest.mtimeMs) {
        latest = { path: abs, mtimeMs };
      }
    }
  }
  return latest ? latest.path : null;
}

function findFallbackVcd(projectRootDir) {
  const roots = [
    path.join(projectRootDir, "output"),
    path.join(projectRootDir, "work"),
    path.join(projectRootDir, "vivado_project"),
    projectRootDir,
  ];
  for (const root of roots) {
    const hit = findLatestFileRecursive(root, ".vcd");
    if (hit) return hit;
  }
  return null;
}

function resolveCompileInputs(projectRoot, request, manifestContext) {
  const tbFileAbs = path.resolve(projectRoot, request.tbRelPath);
  const tbDirAbs = path.dirname(tbFileAbs);
  const srcFileList = uniqueSortedPaths(
    (manifestContext.srcFiles || [])
      .filter((row) => /\.(v|sv)$/i.test(row))
      .map((row) => path.resolve(row))
  );

  let tbFileList = uniqueSortedPaths(
    (manifestContext.tbFiles || [])
      .filter((row) => /\.(v|sv)$/i.test(row))
      .map((row) => path.resolve(row))
  );

  if (tbFileList.length === 0 && fs.existsSync(tbFileAbs)) {
    tbFileList.push(tbFileAbs);
  }
  if (srcFileList.length === 0) {
    throw new Error("Error: manifest resolved src_files is empty.");
  }
  if (fs.existsSync(tbFileAbs) && !tbFileList.find((row) => path.resolve(row) === path.resolve(tbFileAbs))) {
    tbFileList.push(tbFileAbs);
  }
  if (tbFileList.length === 0) {
    throw new Error("Error: manifest resolved tb_files is empty.");
  }

  const beforeFilterCount = tbFileList.length;
  if (fs.existsSync(tbDirAbs)) {
    const scopedTbFiles = tbFileList.filter((row) => isPathWithin(tbDirAbs, row));
    if (scopedTbFiles.length > 0) {
      tbFileList = uniqueSortedPaths(scopedTbFiles);
    }
  }
  if (fs.existsSync(tbFileAbs) && !tbFileList.find((row) => path.resolve(row) === path.resolve(tbFileAbs))) {
    tbFileList.push(path.resolve(tbFileAbs));
  }
  tbFileList = uniqueSortedPaths(tbFileList);

  const tbRootAbs = path.join(projectRoot, "tb");
  const manifestIncDirs = uniqueSortedPaths((manifestContext.incDirs || []).map((row) => path.resolve(row)));
  const includeDirs = uniqueSortedPaths([
    ...manifestIncDirs.filter((dir) => !isPathWithin(tbRootAbs, dir) || isPathWithin(tbDirAbs, dir)),
    ...srcFileList.map((row) => path.dirname(row)),
    ...tbFileList.map((row) => path.dirname(row)),
  ]);

  return {
    srcFileList,
    tbFileList,
    includeDirs,
    tbFileAbs,
    tbDirAbs,
    tbScopeBeforeFilter: beforeFilterCount,
  };
}

function buildVivadoTclContent(params) {
  const safeTestName = params.testName
    ? String(params.testName).replace(/[^A-Za-z0-9_.-]/g, "_")
    : "";
  const plusArgLine = safeTestName
    ? `set_property -name XSIM.SIMULATE.XSIM.MORE_OPTIONS -value "-testplusarg TESTNAME=${safeTestName}" -objects $fs`
    : "";

  return `# Auto-generated by sim_generate_report_cli.js
set project_name "${params.projectName}"
set project_dir "${toTclPath(params.projectDir)}"
set src_files [list ${toTclList(params.srcFiles)}]
set tb_files [list ${toTclList(params.tbFiles)}]
set include_dirs [list ${toTclList(params.includeDirs)}]

create_project -force $project_name $project_dir -part xc7a35tcpg236-1
if {[llength $src_files] > 0} { add_files -norecurse $src_files }
if {[llength $tb_files] > 0} { add_files -fileset sim_1 -norecurse $tb_files }
if {[llength $include_dirs] > 0} {
    catch { set_property include_dirs $include_dirs [get_filesets sources_1] }
    catch { set_property include_dirs $include_dirs [get_filesets sim_1] }
}

set fs [get_filesets sim_1]
set_property top ${params.topModule} $fs
set_property XSIM.SIMULATE.RUNTIME {${params.simTime}} $fs
${plusArgLine}
update_compile_order -fileset sim_1
launch_simulation
if {[catch {run ${params.simTime}} run_err]} {
    puts "Error during simulation run: $run_err"
}
catch {close_sim}
close_project
exit
`;
}

function parseRunLog(logFilePath) {
  const summary = {
    hasEnvReport: false,
    checkedCount: 0,
    errorCount: NaN,
    hasFatal: false,
  };
  if (!fs.existsSync(logFilePath)) return summary;

  const raw = fs.readFileSync(logFilePath, "utf8");
  const matches = [...raw.matchAll(/ENV report:\s*checked=(\d+)\s+errors=(\d+)/g)];
  if (matches.length > 0) {
    const last = matches[matches.length - 1];
    summary.hasEnvReport = true;
    summary.checkedCount = Number(last[1]);
    summary.errorCount = Number(last[2]);
  }
  summary.hasFatal = /\$fatal|\[ASSERT\]|Scoreboard mismatches found|Coverage closure failed/i.test(raw);
  return summary;
}

function writeRegressionSummary(summaryPath, rows) {
  const lines = [
    "# Vivado Regression Summary",
    "",
    "| TESTNAME | Result | Checked | Errors | Reason |",
    "|---|---:|---:|---:|---|",
  ];

  for (const row of rows) {
    lines.push(
      `| ${row.testName} | ${row.pass ? "PASS" : "FAIL"} | ${row.checkedCount} | ${Number.isFinite(row.errorCount) ? row.errorCount : "-"} | ${row.reason} |`
    );
  }

  const passCount = rows.filter((row) => row.pass).length;
  lines.push("");
  lines.push(`- Total: ${rows.length}`);
  lines.push(`- Pass: ${passCount}`);
  lines.push(`- Fail: ${rows.length - passCount}`);
  lines.push("");
  fs.writeFileSync(summaryPath, lines.join("\n"), "utf8");
}

module.exports = {
  buildVivadoTclContent,
  findFallbackVcd,
  parseRunLog,
  resolveCompileInputs,
  slugify,
  writeRegressionSummary,
};
