const fs = require("fs");
const path = require("path");
const { execSync } = require("child_process");
const { loadStrictManifestContext } = require("../../../shared/application/manifest_contract_loader");
const { writeSimulationReportHtml } = require("./sim_report_pipeline_service");
const {
  uniqueStrings,
  normalizeNumber,
  normalizeScenarios,
  createSimulationRunRequest,
  createRegressionRow,
  createWaveArtifactSet,
  createSimulationRunResult,
} = require("../domain/simulation_contracts");
const {
  createRunSummary,
  createArtifactRecord,
} = require("../../../shared/domain/run_contracts");
const { writeJsonFile } = require("../../../shared/application/json_file_service");
const { appendRunEntry } = require("../../../shared/application/run_registry_service");
const { writeRegressionDashboard } = require("./regression_dashboard_service");

function parseArgs(argv) {
  let configArg = "";
  let manifestJsonArg = "";

  for (let i = 0; i < argv.length; i += 1) {
    const arg = String(argv[i] || "");
    if (arg === "--manifest-json") {
      i += 1;
      if (i >= argv.length) throw new Error("--manifest-json requires a value");
      manifestJsonArg = argv[i];
      continue;
    }
    if (arg.startsWith("--manifest-json=")) {
      manifestJsonArg = arg.slice("--manifest-json=".length);
      continue;
    }
    if (arg.startsWith("--")) {
      throw new Error(`Unknown argument: ${arg}`);
    }
    if (!configArg) {
      configArg = arg;
      continue;
    }
    throw new Error(`Unknown argument: ${arg}`);
  }

  if (!configArg || !manifestJsonArg) {
    throw new Error("Usage: node generate_report.js <path_to_config.json> --manifest-json <path>");
  }

  return {
    configPath: path.resolve(configArg),
    manifestJsonPath: path.resolve(manifestJsonArg),
  };
}

function slugify(text) {
  return String(text || "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .slice(0, 64) || "run";
}

function uniqueSortedPaths(rows) {
  return Array.from(new Set((rows || []).map((row) => path.resolve(row)))).sort((a, b) =>
    a.localeCompare(b)
  );
}

function isPathWithin(parentAbs, targetAbs) {
  const parent = path.resolve(parentAbs);
  const target = path.resolve(targetAbs);
  const rel = path.relative(parent, target);
  return rel === "" || (!rel.startsWith("..") && !path.isAbsolute(rel));
}

function ensureDir(dirPath) {
  if (!fs.existsSync(dirPath)) {
    fs.mkdirSync(dirPath, { recursive: true });
  }
}

function createRunStamp() {
  const now = new Date();
  const yyyy = now.getFullYear();
  const mm = String(now.getMonth() + 1).padStart(2, "0");
  const dd = String(now.getDate()).padStart(2, "0");
  const hh = String(now.getHours()).padStart(2, "0");
  const mi = String(now.getMinutes()).padStart(2, "0");
  const ss = String(now.getSeconds()).padStart(2, "0");
  const ms = String(now.getMilliseconds()).padStart(3, "0");
  return `${yyyy}${mm}${dd}_${hh}${mi}${ss}_${ms}`;
}

function toTclPath(value) {
  return String(value || "").replace(/\\/g, "/");
}

function toTclList(paths) {
  return (paths || []).map((value) => `{${toTclPath(value)}}`).join(" ");
}

function buildVivadoTclContent(params) {
  const safeTestName = params.testName
    ? String(params.testName).replace(/[^A-Za-z0-9_.-]/g, "_")
    : "";
  const plusArgLine = safeTestName
    ? `set_property -name XSIM.SIMULATE.XSIM.MORE_OPTIONS -value "-testplusarg TESTNAME=${safeTestName}" -objects $fs`
    : "";

  return `# Auto-generated by simulation_run_service.js
set project_name "${params.projectName}"
set project_dir "${toTclPath(params.projectDir)}"
set src_files [list ${toTclList(params.srcFiles)}]
set tb_files [list ${toTclList(params.tbFiles)}]
set include_dirs [list ${toTclList(params.includeDirs)}]

create_project -force $project_name $project_dir -part xc7a35tcpg236-1
if {[llength $src_files] > 0} { add_files -norecurse $src_files }
if {[llength $tb_files] > 0} { add_files -fileset sim_1 -norecurse $tb_files }
if {[llength $include_dirs] > 0} {
    catch { set_property include_dirs $include_dirs [get_filesets sources_1] }
    catch { set_property include_dirs $include_dirs [get_filesets sim_1] }
}

set fs [get_filesets sim_1]
set_property top ${params.topModule} $fs
set_property XSIM.SIMULATE.RUNTIME {${params.simTime}} $fs
${plusArgLine}
update_compile_order -fileset sim_1
launch_simulation
if {[catch {run ${params.simTime}} run_err]} {
    puts "Error during simulation run: $run_err"
}
catch {close_sim}
close_project
exit
`;
}

function runVivadoBatch(tclFilePath, logFilePath, journalFilePath, workDir) {
  try {
    const vivadoCmd = `vivado -mode batch -source "${tclFilePath}" -log "${logFilePath}" -journal "${journalFilePath}" -notrace`;
    execSync(vivadoCmd, { stdio: "inherit", cwd: workDir, maxBuffer: 1024 * 1024 * 10 });
    return { ok: true };
  } catch (err) {
    return { ok: false, error: err };
  }
}

function parseRunLog(logFilePath) {
  const summary = {
    hasEnvReport: false,
    checkedCount: 0,
    errorCount: NaN,
    hasFatal: false,
  };
  if (!fs.existsSync(logFilePath)) return summary;

  const raw = fs.readFileSync(logFilePath, "utf8");
  const matches = [...raw.matchAll(/ENV report:\s*checked=(\d+)\s+errors=(\d+)/g)];
  if (matches.length > 0) {
    const last = matches[matches.length - 1];
    summary.hasEnvReport = true;
    summary.checkedCount = Number(last[1]);
    summary.errorCount = Number(last[2]);
  }
  summary.hasFatal = /\$fatal|\[ASSERT\]|Scoreboard mismatches found|Coverage closure failed/i.test(raw);
  return summary;
}

function buildRegressionSummaryMarkdown(rows) {
  const lines = [
    "# Vivado Regression Summary",
    "",
    "| TESTNAME | Result | Checked | Errors | Reason |",
    "|---|---:|---:|---:|---|",
  ];
  for (const row of rows || []) {
    lines.push(`| ${row.testName} | ${row.pass ? "PASS" : "FAIL"} | ${row.checkedCount} | ${row.errorCount ?? "-"} | ${row.reason} |`);
  }
  lines.push("");
  const passCount = (rows || []).filter((row) => row.pass).length;
  lines.push(`- Total: ${(rows || []).length}`);
  lines.push(`- Pass: ${passCount}`);
  lines.push(`- Fail: ${(rows || []).length - passCount}`);
  lines.push("");
  return `${lines.join("\n")}\n`;
}

function writeRegressionSummary(summaryPath, rows) {
  fs.writeFileSync(summaryPath, buildRegressionSummaryMarkdown(rows), "utf8");
}

function findLatestFileRecursive(rootDir, ext) {
  if (!fs.existsSync(rootDir)) return null;
  let latest = null;
  const stack = [rootDir];
  while (stack.length > 0) {
    const current = stack.pop();
    const entries = fs.readdirSync(current, { withFileTypes: true });
    for (const entry of entries) {
      const abs = path.join(current, entry.name);
      if (entry.isDirectory()) {
        stack.push(abs);
        continue;
      }
      if (!entry.isFile()) continue;
      if (path.extname(entry.name).toLowerCase() !== ext) continue;
      const mtimeMs = fs.statSync(abs).mtimeMs;
      if (!latest || mtimeMs > latest.mtimeMs) {
        latest = { path: abs, mtimeMs };
      }
    }
  }
  return latest ? latest.path : null;
}

function findFallbackVcd(projectRootDir) {
  const roots = [
    path.join(projectRootDir, "output"),
    path.join(projectRootDir, "work"),
    path.join(projectRootDir, "vivado_project"),
    projectRootDir,
  ];
  for (const root of roots) {
    const hit = findLatestFileRecursive(root, ".vcd");
    if (hit) return hit;
  }
  return null;
}

function createSimulationContext(configPath, manifestJsonPath) {
  if (!fs.existsSync(configPath)) {
    throw new Error(`Config file not found at ${configPath}`);
  }

  const config = JSON.parse(fs.readFileSync(configPath, "utf-8"));
  const projectRoot = path.dirname(configPath);
  const manifestContext = loadStrictManifestContext(projectRoot, manifestJsonPath);
  const normalizedScenarios = normalizeScenarios(config.scenarios);
  const cfg = config.config || {};

  return {
    request: createSimulationRunRequest({
      configPath,
      manifestJsonPath,
      projectRoot,
      cfg,
      scenarios: normalizedScenarios,
    }),
    config,
    cfg,
    projectRoot,
    manifestContext,
    normalizedScenarios,
  };
}

function resolveSimulationInputs(ctx) {
  const { request, cfg, projectRoot, manifestContext, normalizedScenarios } = ctx;
  const maxScenarioEndNs = normalizedScenarios.reduce((maxEnd, scenario) =>
    Math.max(maxEnd, scenario.start_ns + scenario.duration_ns), 0);
  const requestedTestNames = uniqueStrings(Array.isArray(cfg.test_names) ? cfg.test_names : []);
  const simDurationNs = Math.max(normalizeNumber(cfg.sim_duration_ns, 0), maxScenarioEndNs + 10000);
  const simTime = simDurationNs > 0 ? `${simDurationNs / 1000000} ms` : "5 ms";
  const topModule = cfg.top_module || manifestContext.snapshot.top || "tb_Top";
  const projectName = cfg.project_name || manifestContext.snapshot.projectName || path.basename(projectRoot);
  const tbRelPath = cfg.tb_file || manifestContext.result.resolved.tb_files[0] || "";
  const vcdRelPath = cfg.vcd_file || "output/mcp_sim_wave.vcd";
  const htmlRelPath = cfg.html_file || `output/view_wave_${topModule}.html`;
  const tbFileAbs = path.resolve(projectRoot, tbRelPath);
  const tbDirAbs = path.dirname(tbFileAbs);
  const srcFileList = uniqueSortedPaths(
    (manifestContext.srcFiles || []).filter((filePath) => /\.(v|sv)$/i.test(filePath)).map((filePath) => path.resolve(filePath))
  );
  let tbFileList = uniqueSortedPaths(
    (manifestContext.tbFiles || []).filter((filePath) => /\.(v|sv)$/i.test(filePath)).map((filePath) => path.resolve(filePath))
  );
  if (tbFileList.length === 0 && fs.existsSync(tbFileAbs)) {
    tbFileList.push(tbFileAbs);
  }
  if (!srcFileList.length) throw new Error("manifest resolved src_files is empty.");
  if (fs.existsSync(tbFileAbs) && !tbFileList.find((filePath) => path.resolve(filePath) === path.resolve(tbFileAbs))) {
    tbFileList.push(tbFileAbs);
  }
  if (!tbFileList.length) throw new Error("manifest resolved tb_files is empty.");

  if (fs.existsSync(tbDirAbs)) {
    const scopedTbFiles = tbFileList.filter((filePath) => isPathWithin(tbDirAbs, filePath));
    if (scopedTbFiles.length > 0) {
      tbFileList = uniqueSortedPaths(scopedTbFiles);
    }
  }
  if (fs.existsSync(tbFileAbs) && !tbFileList.find((filePath) => path.resolve(filePath) === path.resolve(tbFileAbs))) {
    tbFileList.push(path.resolve(tbFileAbs));
  }
  tbFileList = uniqueSortedPaths(tbFileList);

  const tbRootAbs = path.join(projectRoot, "tb");
  const manifestIncDirs = uniqueSortedPaths((manifestContext.incDirs || []).map((dirPath) => path.resolve(dirPath)));
  const includeDirs = uniqueSortedPaths([
    ...manifestIncDirs.filter((dirPath) => !isPathWithin(tbRootAbs, dirPath) || isPathWithin(tbDirAbs, dirPath)),
    ...srcFileList.map((filePath) => path.dirname(filePath)),
    ...tbFileList.map((filePath) => path.dirname(filePath)),
  ]);

  return {
    request,
    cfg,
    projectRoot,
    manifestContext,
    normalizedScenarios,
    requestedTestNames,
    simTime,
    topModule,
    projectName,
    tbRelPath,
    vcdRelPath,
    htmlRelPath,
    tbFileAbs,
    tbDirAbs,
    srcFileList,
    tbFileList,
    includeDirs,
  };
}

function writeRunArtifacts(projectRoot, manifestJsonPath, runResult) {
  const artifacts = [];
  const runStamp = runResult.runStamp || createRunStamp();
  const historyDir = path.join(projectRoot, "output", "history", "simulation_report", runStamp);
  ensureDir(historyDir);
  if (runResult.htmlFile) {
    artifacts.push(createArtifactRecord({ kind: "simulation_report_html", path: runResult.htmlFile }));
  }
  if (runResult.vcdFile) {
    artifacts.push(createArtifactRecord({ kind: "simulation_waveform_vcd", path: runResult.vcdFile }));
  }
  for (const generatedFile of runResult.generatedFiles || []) {
    artifacts.push(createArtifactRecord({
      kind: generatedFile.kind || "wavedrom_case_json",
      path: generatedFile.file,
      label: generatedFile.title || path.basename(generatedFile.file || ""),
    }));
  }
  const passCount = (runResult.regressionRows || []).filter((row) => row.pass).length;
  const failCount = (runResult.regressionRows || []).filter((row) => !row.pass).length;

  const summary = createRunSummary({
    tool: "simulation_report",
    projectRoot,
    manifestJsonPath,
    status: runResult.status,
    warnings: runResult.warnings,
    artifacts,
    details: {
      projectName: runResult.projectName,
      topModule: runResult.topModule,
      tbFile: runResult.tbFile,
      mode: runResult.mode || "single_run",
      passCount,
      failCount,
      regressionSummaryJsonPath: runResult.regressionSummaryJsonPath || "",
      regressionRows: runResult.regressionRows,
    },
  });
  const historySummaryPath = writeJsonFile(path.join(historyDir, "run_summary.json"), summary);
  const summaryPath = writeJsonFile(path.join(projectRoot, "output", "run_summary.json"), summary);
  appendRunEntry(projectRoot, {
    tool: "simulation_report",
    projectRoot,
    manifestJsonPath,
    status: runResult.status,
    outputs: artifacts,
    summaryPath: historySummaryPath,
    metadata: {
      projectName: runResult.projectName,
      topModule: runResult.topModule,
      regressionCount: runResult.regressionRows.length,
      mode: runResult.mode || "single_run",
      passCount,
      failCount,
    },
  });
  return {
    summary,
    summaryPath,
    historySummaryPath,
  };
}

function runRegressionMode(inputs, workDir, tclDir, simLogDir, outDirFs) {
  const regressionRows = [];
  const tbBase = path.basename(inputs.tbFileAbs, path.extname(inputs.tbFileAbs));
  const runStamp = createRunStamp();
  const historyDir = path.join(outDirFs, "history", "simulation_report", runStamp);
  ensureDir(historyDir);
  for (let index = 0; index < inputs.requestedTestNames.length; index += 1) {
    const testName = inputs.requestedTestNames[index];
    const runSlug = `${String(index + 1).padStart(2, "0")}_${slugify(testName)}`;
    const runTclPath = path.join(tclDir, `run_sim_${runSlug}.tcl`);
    const runProjectDir = path.join(inputs.projectRoot, "work", "regression", runSlug);
    const runLogPath = path.join(simLogDir, `vivado_regression_${runSlug}.log`);
    const runJouPath = path.join(simLogDir, `vivado_regression_${runSlug}.jou`);
    const runProjectName = `mcp_reg_${runSlug}`;

    const runTcl = buildVivadoTclContent({
      projectName: runProjectName,
      projectDir: runProjectDir,
      srcFiles: inputs.srcFileList,
      tbFiles: inputs.tbFileList,
      includeDirs: inputs.includeDirs,
      topModule: inputs.topModule,
      simTime: inputs.simTime,
      testName,
    });
    fs.writeFileSync(runTclPath, runTcl, "utf8");

    console.log(`[Regression] Running TESTNAME=${testName}`);
    const runResult = runVivadoBatch(runTclPath, runLogPath, runJouPath, workDir);
    const logResult = parseRunLog(runLogPath);

    let reason = "ok";
    if (!runResult.ok) reason = "vivado_failed";
    else if (!logResult.hasEnvReport) reason = "missing_env_report";
    else if (!Number.isFinite(logResult.errorCount) || logResult.errorCount !== 0) reason = "scoreboard_errors";
    else if (logResult.hasFatal) reason = "fatal_or_assert";

    const pass = reason === "ok";
    const row = createRegressionRow({
      testName,
      pass,
      checkedCount: logResult.checkedCount,
      errorCount: logResult.errorCount,
      reason,
      logPath: runLogPath,
    });
    regressionRows.push(row);
    console.log(`[Regression] ${testName}: ${pass ? "PASS" : "FAIL"} (reason=${reason})`);
  }

  const summaryPath = path.join(outDirFs, `regression_${tbBase}.md`);
  const summaryJsonPath = path.join(outDirFs, `regression_${tbBase}.json`);
  const runSummaryPath = path.join(historyDir, `regression_${tbBase}.md`);
  const runSummaryJsonPath = path.join(historyDir, `regression_${tbBase}.json`);
  const regressionPayload = {
    schemaVersion: 1,
    type: "regression_run",
    generatedAt: new Date().toISOString(),
    projectName: inputs.projectName,
    topModule: inputs.topModule,
    rows: regressionRows,
  };
  writeRegressionSummary(runSummaryPath, regressionRows);
  writeRegressionSummary(summaryPath, regressionRows);
  writeJsonFile(runSummaryJsonPath, regressionPayload);
  writeJsonFile(summaryJsonPath, regressionPayload);
  console.log(`Regression summary: ${summaryPath}`);

  const failCount = regressionRows.filter((row) => !row.pass).length;
  return {
    regressionRows,
    failCount,
    runStamp,
    summaryPath,
    summaryJsonPath,
    runSummaryPath,
    runSummaryJsonPath,
    summaryArtifacts: [
      { file: runSummaryPath, title: path.basename(runSummaryPath), description: "", start_ns: 0, duration_ns: 0, kind: "regression_run_markdown" },
      { file: runSummaryJsonPath, title: path.basename(runSummaryJsonPath), description: "", start_ns: 0, duration_ns: 0, kind: "regression_run_json" },
    ],
  };
}

function runScenarioExtraction(inputs, outDirFs, vcdFile) {
  const toolsDir = path.resolve(__dirname, "..", "adapters", "cli");
  const vcdToWavedromScript = path.join(toolsDir, "sim_convert_vcd_wavedrom_legacy_cli.js");
  const nodeExec = process.execPath;
  const generatedFiles = [];

  console.log(`Processing ${inputs.normalizedScenarios.length} scenarios for project: ${inputs.projectName}`);
  for (const scenario of inputs.normalizedScenarios) {
    if (!scenario.signals.length) {
      console.warn(`[${scenario.title}] skipped: no signals.`);
      continue;
    }
    const jsonFilename = `wave_${scenario.id}.json`;
    const outFile = path.join(outDirFs, jsonFilename);
    const signalCsv = scenario.signals.join(",");
    const cmd = `"${nodeExec}" "${vcdToWavedromScript}" "${vcdFile}" "${outFile}" ${scenario.start_ns} ${scenario.duration_ns} "${signalCsv}" ${scenario.sample_step_ns}`;
    console.log(`[${scenario.title}] Extracting waveform...`);
    try {
      execSync(cmd, { stdio: "inherit" });
      if (fs.existsSync(outFile)) {
        generatedFiles.push(createWaveArtifactSet({
          file: outFile,
          title: scenario.title,
          description: scenario.description || "",
          start_ns: scenario.start_ns,
          duration_ns: scenario.duration_ns,
          jsonData: fs.readFileSync(outFile, "utf8"),
        }));
      }
    } catch (err) {
      console.error(`Failed to process scenario ${scenario.id}: ${err.message}`);
    }
  }

  return generatedFiles;
}

function runSimulationReport(configPath, manifestJsonPath) {
  const ctx = createSimulationContext(configPath, manifestJsonPath);
  const inputs = resolveSimulationInputs(ctx);
  const outDirFs = path.join(inputs.projectRoot, "output");
  const tclDir = path.join(inputs.projectRoot, "tcl");
  const workDir = path.join(inputs.projectRoot, "work");
  const simLogDir = path.join(inputs.projectRoot, "log", "vivado_sim");
  ensureDir(tclDir);
  ensureDir(workDir);
  ensureDir(outDirFs);
  ensureDir(simLogDir);

  if (inputs.requestedTestNames.length > 0) {
    const regressionResult = runRegressionMode(inputs, workDir, tclDir, simLogDir, outDirFs);
    const runResult = createSimulationRunResult({
      projectName: inputs.projectName,
      topModule: inputs.topModule,
      tbFile: inputs.tbRelPath,
      htmlFile: "",
      vcdFile: "",
      generatedFiles: regressionResult.summaryArtifacts,
      regressionRows: regressionResult.regressionRows,
      warnings: [],
      status: regressionResult.failCount > 0 ? "failed" : "ok",
      mode: "regression",
      runStamp: regressionResult.runStamp,
      regressionSummaryPath: regressionResult.runSummaryPath,
      regressionSummaryJsonPath: regressionResult.runSummaryJsonPath,
      latestRegressionSummaryPath: regressionResult.summaryPath,
      latestRegressionSummaryJsonPath: regressionResult.summaryJsonPath,
    });
    const written = writeRunArtifacts(inputs.projectRoot, manifestJsonPath, runResult);
    const dashboard = writeRegressionDashboard(inputs.projectRoot);
    runResult.regressionDashboardPath = dashboard.summaryPath;
    runResult.regressionDashboardMarkdownPath = dashboard.markdownPath;
    return {
      mode: "regression",
      exitCode: regressionResult.failCount > 0 ? 1 : 0,
      summaryPath: written.summaryPath,
      historySummaryPath: written.historySummaryPath,
      regressionSummaryPath: regressionResult.summaryPath,
      regressionSummaryJsonPath: regressionResult.summaryJsonPath,
      regressionDashboardPath: dashboard.summaryPath,
      regressionDashboardMarkdownPath: dashboard.markdownPath,
      runResult,
    };
  }

  const tclPath = path.join(tclDir, "run_sim_autogen.tcl");
  const tclContent = buildVivadoTclContent({
    projectName: "mcp_sim_proj",
    projectDir: workDir,
    srcFiles: inputs.srcFileList,
    tbFiles: inputs.tbFileList,
    includeDirs: inputs.includeDirs,
    topModule: inputs.topModule,
    simTime: inputs.simTime,
    testName: "",
  });
  fs.writeFileSync(tclPath, tclContent, "utf8");
  console.log(`TCL script generated: ${tclPath}`);

  console.log("Running Vivado Simulation...");
  const singleRunLogPath = path.join(simLogDir, "vivado_sim.log");
  const singleRunJouPath = path.join(simLogDir, "vivado_sim.jou");
  const singleRunResult = runVivadoBatch(tclPath, singleRunLogPath, singleRunJouPath, workDir);
  if (!singleRunResult.ok) {
    throw new Error("Vivado simulation failed. Check logs.");
  }

  let vcdFile = path.resolve(inputs.projectRoot, inputs.vcdRelPath);
  const htmlFile = path.resolve(inputs.projectRoot, inputs.htmlRelPath);
  ensureDir(path.dirname(htmlFile));

  if (!fs.existsSync(vcdFile)) {
    const fallbackVcd = findFallbackVcd(inputs.projectRoot);
    if (fallbackVcd) {
      ensureDir(path.dirname(vcdFile));
      try {
        fs.copyFileSync(fallbackVcd, vcdFile);
        console.warn(`[WARN] Primary VCD not found. Copied fallback VCD: ${fallbackVcd}`);
      } catch {
        vcdFile = fallbackVcd;
        console.warn(`[WARN] Primary VCD not found. Using fallback VCD directly: ${fallbackVcd}`);
      }
    }
  }
  if (!fs.existsSync(vcdFile)) {
    throw new Error(`VCD file not found at ${vcdFile}`);
  }

  const generatedFiles = runScenarioExtraction(inputs, outDirFs, vcdFile);
  writeSimulationReportHtml(htmlFile, inputs.projectName, generatedFiles, new Date());
  console.log(`SUCCESS: Report generated at: ${htmlFile}`);

  const runResult = createSimulationRunResult({
    projectName: inputs.projectName,
    topModule: inputs.topModule,
    tbFile: inputs.tbRelPath,
    htmlFile,
    vcdFile,
    generatedFiles,
    regressionRows: [],
    warnings: [],
    status: "ok",
    mode: "single_run",
  });
  const written = writeRunArtifacts(inputs.projectRoot, manifestJsonPath, runResult);
  return {
    mode: "single_run",
    exitCode: 0,
    summaryPath: written.summaryPath,
    historySummaryPath: written.historySummaryPath,
    runResult,
  };
}

module.exports = {
  parseArgs,
  buildVivadoTclContent,
  runVivadoBatch,
  parseRunLog,
  writeRegressionSummary,
  runSimulationReport,
};
