const fs = require('fs');
const { execSync } = require('child_process');
const path = require('path');

// 1. Get Config File Path from Argument
const args = process.argv.slice(2);
if (args.length < 1) {
    console.error("Usage: node generate_report.js <path_to_config.json>");
    process.exit(1);
}

const configPath = path.resolve(args[0]);
if (!fs.existsSync(configPath)) {
    console.error(`Error: Config file not found at ${configPath}`);
    process.exit(1);
}

// 2. Load Configuration
console.log(`Loading configuration from: ${configPath}`);
const config = JSON.parse(fs.readFileSync(configPath, 'utf-8'));
const projectRoot = path.dirname(configPath); // Config file location is the project root anchor
const cfg = config.config || {};
const rawScenarios = Array.isArray(config.scenarios) ? config.scenarios : [];

const normalizeNumber = (value, fallback) => {
    const n = Number(value);
    return Number.isFinite(n) ? n : fallback;
};

const normalizedScenarios = rawScenarios.map((scenario, index) => {
    const startNs = Math.max(0, Math.round(normalizeNumber(scenario.start_ns, 0)));
    const durationNs = Math.max(1, Math.round(normalizeNumber(scenario.duration_ns, 100000)));
    const stepNs = Math.max(1, Math.round(normalizeNumber(scenario.sample_step_ns, 100)));
    const title = scenario.title || `CASE ${index + 1}`;
    const id = scenario.id || `case_${index + 1}`;
    const signals = Array.from(new Set(Array.isArray(scenario.signals) ? scenario.signals.filter(Boolean) : []));

    return {
        ...scenario,
        id,
        title,
        start_ns: startNs,
        duration_ns: durationNs,
        sample_step_ns: stepNs,
        signals
    };
});

const maxScenarioEndNs = normalizedScenarios.reduce((maxEnd, scenario) => {
    return Math.max(maxEnd, scenario.start_ns + scenario.duration_ns);
}, 0);

const simDurationNs = Math.max(
    normalizeNumber(cfg.sim_duration_ns, 0),
    maxScenarioEndNs + 10000
);
const simTime = simDurationNs > 0 ? `${simDurationNs / 1000000} ms` : '5 ms';
const topModule = cfg.top_module || 'tb_Top';
const projectName = cfg.project_name || path.basename(projectRoot);
const vcdRelPath = cfg.vcd_file || 'output/mcp_sim_wave.vcd';
const htmlRelPath = cfg.html_file || `output/view_wave_${topModule}.html`;

// 2.1 Generate TCL Script
console.log("Generating Vivado TCL script...");
const tclPath = path.join(projectRoot, 'tcl', 'run_sim_autogen.tcl');

// Use forward slashes for TCL compatibility
const projDir = path.join(projectRoot, 'work').replace(/\\/g, '/');
const srcDir = path.join(projectRoot, 'src').replace(/\\/g, '/');
const tbDir = path.join(projectRoot, 'tb').replace(/\\/g, '/');
const outDirFs = path.join(projectRoot, 'output');
const outDir = outDirFs.replace(/\\/g, '/');

const tclContent = `# Auto-generated by generate_report.js
set project_name "mcp_sim_proj"
set project_dir "${projDir}"
set src_dir "${srcDir}"
set tb_dir "${tbDir}"
set out_dir "${outDir}"

# Create/Reset Project
create_project -force $project_name $project_dir -part xc7a35tcpg236-1

# Add Sources
add_files $src_dir/
add_files -fileset sim_1 $tb_dir/${topModule}.v

# Set Top
set_property top ${topModule} [get_filesets sim_1]
update_compile_order -fileset sim_1

# Run Simulation
launch_simulation
if {[catch {
    open_vcd "$out_dir/mcp_sim_wave.vcd"
    log_vcd [get_objects -r /${topModule}/*]
    
    run ${simTime}
    
    close_vcd
    close_sim
} err]} {
    puts "Error during simulation: $err"
}

close_project
exit
`;

if (!fs.existsSync(path.dirname(tclPath))) {
    fs.mkdirSync(path.dirname(tclPath), { recursive: true });
}
fs.writeFileSync(tclPath, tclContent);
console.log(`TCL script generated: ${tclPath}`);

// 2.2 Run Simulation (Vivado)
console.log("Running Vivado Simulation...");
try {
    const vivadoCmd = `vivado -mode batch -source "${tclPath}"`;
    // Increase maxBuffer to handle large Vivado output
    execSync(vivadoCmd, { stdio: 'inherit', cwd: path.join(projectRoot, 'work'), maxBuffer: 1024 * 1024 * 10 });
} catch (e) {
    console.error("Vivado simulation failed. Check logs.");
    // We might continue if VCD exists, but usually we stop.
    // process.exit(1); 
}

// 3. Resolve Paths (Relative to Config File)
const toolsDir = __dirname; // Assuming this script is in /tools
const vcd2wavedromScript = path.join(toolsDir, 'vcd2wavedrom.js');

const vcdFile = path.resolve(projectRoot, vcdRelPath);
const htmlFile = path.resolve(projectRoot, htmlRelPath);
const outputDir = path.dirname(htmlFile);

// Ensure output directory exists
if (!fs.existsSync(outDirFs)) {
    fs.mkdirSync(outDirFs, { recursive: true });
}
if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
}

// 4. Check VCD Existence
if (!fs.existsSync(vcdFile)) {
    console.error(`Error: VCD file not found at ${vcdFile}`);
    console.error("Please run the simulation first.");
    process.exit(1);
}

// 5. Process Scenarios (Generate JSONs)
console.log(`Processing ${normalizedScenarios.length} scenarios for project: ${projectName}`);
const generatedFiles = [];

normalizedScenarios.forEach(scenario => {
    if (scenario.signals.length === 0) {
        console.warn(`[${scenario.title}] skipped: no signals.`);
        return;
    }

    const jsonFilename = `wave_${scenario.id}.json`;
    const outFile = path.join(outDirFs, jsonFilename);
    const signals = scenario.signals.join(',');
    
    // Command: node vcd2wavedrom.js input output start duration signals step
    const cmd = `node "${vcd2wavedromScript}" "${vcdFile}" "${outFile}" ${scenario.start_ns} ${scenario.duration_ns} "${signals}" ${scenario.sample_step_ns}`;
    
    console.log(`[${scenario.title}] Extracting waveform...`);
    try {
        execSync(cmd, { stdio: 'inherit' });
        if (fs.existsSync(outFile)) {
            generatedFiles.push({
                file: outFile,
                title: scenario.title,
                description: scenario.description || "",
                start_ns: scenario.start_ns,
                duration_ns: scenario.duration_ns
            });
        }
    } catch (e) {
        console.error(`Failed to process scenario ${scenario.id}:`, e.message);
    }
});

// 6. Generate HTML Report
console.log("Compiling HTML report...");

let htmlContent = `<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>${projectName} - Simulation Report</title>
<script src="https://cdnjs.cloudflare.com/ajax/libs/wavedrom/3.5.0/skins/default.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/wavedrom/3.5.0/wavedrom.min.js"></script>
<style>
body { font-family: 'Segoe UI', Arial, sans-serif; margin: 0; padding: 20px; background-color: #f4f7f6; color: #333; }
.header { text-align: center; margin-bottom: 40px; padding-bottom: 20px; border-bottom: 1px solid #ddd; }
.header h1 { margin: 0; color: #2c3e50; }
.header p { color: #7f8c8d; }
.wave-card { 
    background: white; 
    border-radius: 8px; 
    box-shadow: 0 2px 10px rgba(0,0,0,0.05); 
    padding: 20px; 
    margin-bottom: 30px; 
}
.wave-card h2 { margin-top: 0; font-size: 1.2rem; color: #2980b9; border-left: 4px solid #3498db; padding-left: 10px; }
.wave-card p { color: #666; font-size: 0.9rem; margin-bottom: 15px; }
.wave-view { overflow-x: auto; padding: 10px 0; }
</style>
</head>
<body onload="WaveDrom.ProcessAll()">
<div class="header">
    <h1>${projectName}</h1>
    <p>Simulation Report | Generated on ${new Date().toLocaleString()}</p>
</div>
`;

generatedFiles.forEach(item => {
    const jsonData = fs.readFileSync(item.file, 'utf-8');
    const endNs = item.start_ns + item.duration_ns;
    const runtimeInfo = `Runtime: ${item.duration_ns} ns (Window: ${item.start_ns} ns ~ ${endNs} ns)`;
    htmlContent += `
    <div class="wave-card">
        <h2>${item.title}</h2>
        <p>${runtimeInfo}</p>
        ${item.description ? `<p>${item.description}</p>` : ''}
        <div class="wave-view">
            <script type="WaveDrom">
            ${jsonData}
            </script>
        </div>
    </div>
    `;
});

if (generatedFiles.length === 0) {
    htmlContent += `
    <div class="wave-card">
        <h2>No Waveforms</h2>
        <p>No scenario produced output JSON. Check TEST/@WAVE/@RUNTIME BEGIN:time and END:time directives in your testbench.</p>
    </div>
    `;
}

htmlContent += `
</body>
</html>`;

fs.writeFileSync(htmlFile, htmlContent);
console.log(`\nSUCCESS: Report generated at: ${htmlFile}`);
